<a href="https://colab.research.google.com/github/D1emonk/My-repo/blob/dev/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
# Определяем матрицы
A = np.array([[1, 2, 4], [7, 5, -2], [-2, 1, 3]])  # Матрица 3x3
B = np.array([[-1, 0, 3], [2, -6, 1], [-7, 1, 5]])  # Матрица 3x3
C = np.array([[-2, 3], [4, 0], [7, -1]])  # Матрица 3x2

# Операции с матрицами
sum_result = A + B
sub_result = A - B
mul_result1 = np.dot(A, C)
mul_result2 = np.dot(np.dot(A, B), C)

# Вывод результатов
print("Сложение матриц 3x3:")
print(sum_result)

print("\nВычитание матриц 3x3:")
print(sub_result)

print("\nУмножение матрицы 3x3 на 3x2:")
print(mul_result1)

print("\nУмножение двух матрицы 3x3 на одну матрицу  3x2:")
print(mul_result2)


Сложение матриц 3x3:
[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]

Вычитание матриц 3x3:
[[ 2  2  1]
 [ 5 11 -3]
 [ 5  0 -2]]

Умножение матрицы 3x3 на 3x2:
[[34 -1]
 [-8 23]
 [29 -9]]

Умножение двух матрицы 3x3 на одну матрицу  3x2:
[[ 193 -100]
 [ -50   35]
 [  92  -61]]


In [13]:
# Определяем матрицы
A = np.array([[0, 3, 4], [-7, 1, -2], [2, -1, 3]])  # Матрица 3x3
B = np.array([[1, 2, 4], [7, 0, -2], [-3, -2, 5]])  # Матрица 3x3
C = np.array([[-3, 2], [0, 4], [-1, 7]])  # Матрица 3x2

# Операции с матрицами
sum_result = A + B
sub_result = A - B
mul_result1 = np.dot(A, C)
mul_result2 = np.dot(np.dot(A, B), C)

# Вывод результатов
print("Сложение матриц 3x3:")
print(sum_result)

print("\nВычитание матриц 3x3:")
print(sub_result)

print("\nУмножение матрицы 3x3 на 3x2:")
print(mul_result1)

print("\nУмножение двух матрицы 3x3 на одну матрицу  3x2:")
print(mul_result2)

Сложение матриц 3x3:
[[ 1  5  8]
 [ 0  1 -4]
 [-1 -3  8]]

Вычитание матриц 3x3:
[[ -1   1   0]
 [-14   1   0]
 [  5   1  -2]]

Умножение матрицы 3x3 на 3x2:
[[ -4  40]
 [ 23 -24]
 [ -9  21]]

Умножение двух матрицы 3x3 на одну матрицу  3x2:
[[ -41   84]
 [  22 -308]
 [  17  139]]


In [17]:
# Определяем матрицы
A = np.array([[5, 2, 9], [7, 0, -2], [-2, 1, 6]])  # Матрица 3x3
B = np.array([[1, -2, 1], [7, 5, -2], [-2, 8, 3]])  # Матрица 3x3
C = np.array([[-2, 3], [4, 5], [0, -1]])  # Матрица 3x2

# Операции с матрицами
sum_result = A + B
sub_result = A - B
mul_result1 = np.dot(A, C)
mul_result2 = np.dot(np.dot(A, B), C)

# Вывод результатов
print("Сложение матриц 3x3:")
print(sum_result)

print("\nВычитание матриц 3x3:")
print(sub_result)

print("\nУмножение матрицы 3x3 на 3x2:")
print(mul_result1)

print("\nУмножение двух матрицы 3x3 на одну матрицу  3x2:")
print(mul_result2)

Сложение матриц 3x3:
[[ 6  0 10]
 [14  5 -4]
 [-4  9  9]]

Вычитание матриц 3x3:
[[ 4  4  8]
 [ 0 -5  0]
 [ 0 -7  3]]

Умножение матрицы 3x3 на 3x2:
[[ -2  16]
 [-14  23]
 [  8  -7]]

Умножение двух матрицы 3x3 на одну матрицу  3x2:
[[ 286  335]
 [-142 -118]
 [ 242  250]]


In [18]:
# Определяем матрицы
A = np.array([[1, -2, 8], [7, 5, -2], [-2, 3, 0]])  # Матрица 3x3
B = np.array([[0, 2, 4], [1, -3, -2], [-2, 1, 3]])  # Матрица 3x3
C = np.array([[0, 3], [5, -4], [7, -1]])  # Матрица 3x2

# Операции с матрицами
sum_result = A + B
sub_result = A - B
mul_result1 = np.dot(A, C)
mul_result2 = np.dot(np.dot(A, B), C)

# Вывод результатов
print("Сложение матриц 3x3:")
print(sum_result)

print("\nВычитание матриц 3x3:")
print(sub_result)

print("\nУмножение матрицы 3x3 на 3x2:")
print(mul_result1)

print("\nУмножение двух матрицы 3x3 на одну матрицу  3x2:")
print(mul_result2)

Сложение матриц 3x3:
[[ 1  0 12]
 [ 8  2 -4]
 [-4  4  3]]

Вычитание матриц 3x3:
[[ 1 -4  4]
 [ 6  8  0]
 [ 0  2 -3]]

Умножение матрицы 3x3 на 3x2:
[[ 46   3]
 [ 11   3]
 [ 15 -18]]

Умножение двух матрицы 3x3 на одну матрицу  3x2:
[[ 304 -150]
 [  69   27]
 [-163   75]]


In [19]:
# Определяем матрицы
A = np.array([[9, 2, 4], [7, 5, -5], [6, -2, 3]])  # Матрица 3x3
B = np.array([[8, 2, 4], [0, 1, -3], [-2, 1, 6]])  # Матрица 3x3
C = np.array([[-2, 0], [4, 8], [1, -1]])  # Матрица 3x2

# Операции с матрицами
sum_result = A + B
sub_result = A - B
mul_result1 = np.dot(A, C)
mul_result2 = np.dot(np.dot(A, B), C)

# Вывод результатов
print("Сложение матриц 3x3:")
print(sum_result)

print("\nВычитание матриц 3x3:")
print(sub_result)

print("\nУмножение матрицы 3x3 на 3x2:")
print(mul_result1)

print("\nУмножение двух матрицы 3x3 на одну матрицу  3x2:")
print(mul_result2)

Сложение матриц 3x3:
[[17  4  8]
 [ 7  6 -8]
 [ 4 -1  9]]

Вычитание матриц 3x3:
[[ 1  0  0]
 [ 7  4 -2]
 [ 8 -3 -3]]

Умножение матрицы 3x3 на 3x2:
[[ -6  12]
 [  1  45]
 [-17 -19]]

Умножение двух матрицы 3x3 на одну матрицу  3x2:
[[ 22 138]
 [-93 129]
 [ 16  56]]
